### PR TITLE
Merge stable Dev into Master

### PR DESCRIPTION
**Pull request by dcelik**
This marks the v2.0 release of SantosGUI and includes upgrades to homography, video creation, and overall performance.

### CODE REVIEW

**Comment by runnersaw** [comment]
I say :ship: it. Should we create a tag when merged?

**Comment by dcelik** [comment]
Yup, I will create a new release Tag and description when merged.

**Comment by youralien** [comment]
Yup I didn't read this, but I've read most of the PR's that made this. 🚢 it

**Comment by dcelik** [comment]
Will get shipped and tagged once the API Docs are updated.

**Review by jabb1123 — APPROVED** [review]

**Review by runnersaw — APPROVED** [review]
Do it

**Review by jabb1123 — APPROVED** [review]

**Pull request merged**
